dev:
  tags:
    - meao
    - aws
  only:
    - dev
    - master
  variables:
    NAMESPACE: snippets-dev
  script:
    - bin/build_images.sh
    - bin/push2dockerhub.sh
    - CLUSTER_NAME=oregon-b bin/update-config.sh
    

stage:
  tags:
    - meao
    - aws
  only:
    - stage
  variables:
    NAMESPACE: snippets-stage
  script:
    - bin/build_images.sh
    - bin/push2dockerhub.sh
    - CLUSTER_NAME=oregon-b bin/update-config.sh


prod:
  tags:
    - meao
    - aws
  only:
    - prod
  variables:
    NAMESPACE: snippets-prod
  script:
    - bin/build_images.sh
    - bin/push2dockerhub.sh
    - CLUSTER_NAME=frankfurt bin/update-config.sh
    - CLUSTER_NAME=oregon-b bin/update-config.sh
